# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

user_accounts = {}  # Define an empty dictionary to store user accounts

# Function for user sign up
def sign_up():
    print("\nSign Up")
    while True:
        username = input("Enter Username: ")
        if not username:
            print("Username cannot be empty. Please enter a valid username.")
            continue
        password = input("Enter Password: ")
        if not password:
            print("Password cannot be empty. Please enter a valid password.")
            continue
        if username in user_accounts:
            print("Username already exists. Please choose a different username.")
        else:
            user_accounts[username] = password
            print("Sign up successful. You can now login.")
            break

# Function for user login
def login():
    print("\nLogin")
    while True:
        username = input("Enter Username: ")
        password = input("Enter Password: ")
        if username in user_accounts and user_accounts[username] == password:
            print("Login successful.")
            return True
        else:
            print("Invalid username or password. Please try again.")
            choice = input("Do you want to sign up? (yes/no): ").lower()
            if choice == 'yes':
                sign_up()
            elif choice == 'no':
                return False

import datetime
patients = []
doctors = {
    'English': ["Dr.Sujith,contact NO:-885676545,Ratings:-(3/5)", "Dr.Raju,contact NO:-8653456987,Ratings:-(4/5)", "Dr.Raju,contact NO:-8653456987,Ratings:-(4/5)"],
    'Hindi': ["Dr.Kiran,contact NO:-213345678,Ratings:-(3.5/5)", "Dr.Naveen,contact NO:-754569878,Ratings:-(4.3/5)", "Dr.Jerina,contact NO:-63587458,Ratings:-(4.5/5)"],
    'Telugu':["Dr.Kajal,contact NO:-345678998,Ratings:-(4.5/5)","Dr.Nithish,contact NO:-754569878,Ratings:-(4.3/5)","Dr.Vaishnavi,contact NO:-63587458,Ratings:-(4.5/5)"],
    'Kannada':["Dr.Ramu,contact NO:-34567985,Ratings:-(3/5)","Dr.Varshini,contact NO:-345656987,Ratings:-(4/5)","Dr.Anuja,contact NO:-456780987,Ratings:-(3.5/5)"],
    'Tamil':["Dr.Manjunath,contact NO:-456780987,Ratings:-(4.3/5)","Dr.John,contact NO:--0987655689,Ratings:-(4.5/5)","Dr.John,contact NO:--0987655689,Ratings:-(4.5/5)"]
}
appointments = []
def register_patient():
    print("\nPatient Registration:")
    name = input("Enter Your Name: ")
    age = input("Enter Your Age: ")
    gender = input("Enter Your Gender: ")
    phone = input("Enter Your Phone Number: ")
    patient = {'Name': name, 'Age': age, 'Gender': gender, 'Phone':           phone}
    patients.append(patient)
    print("Patient registered successfully!")
def location():
    while True:
        print("\nChoose Hospital location")
        print("1. HAL")
        print("2. MARATHAHALLI")
        print("3. KR PURA")
        choice = input("Enter your choice (1/2/3): ")
        if choice == '1':
            print("Your location is HAL")
            break
        elif choice == '2':
            print("Your location is MARATHAHALLI")
            break
        elif choice == '3':
            print("Your location is KR PURA")
            break
        else:
            print("Invalid choice. Please enter a valid option.")
def problem():
    while True:
        print("\nChoose your problem")
        print("1. Skin Diseases")
        print("2. Respiratory Issues")
        print("3. Heart Diseases")
        print("4. Thyroid Disorders")
        print("5. Diabetes")

        choice = input("Enter your choice (1/2/3/4/5): ")

        if choice == '1':
            print("I am Facing problem from Skin Diseases")
            break
        elif choice == '2':
            print("I am Facing problem Respiratory Issues")
            break
        elif choice == '3':
            print("I am Facing problem Heart Diseases")
            break
        elif choice == '4':
            print("I am Facing problem Thyroid Disorders")
            break
        elif choice == '5':
            print("I am Facing problem Diabetes")
            break
        else:
            print("Invalid choice. Please enter a valid option.")
def display_doctors(language):
    if language in doctors:
        print(f"\nAvailable {language} Doctors:")
        for i, doctor in enumerate(doctors[language], start=1):
            print(f"{i}. {doctor}")
    else:
        print(f"No doctors available for {language}.")
def book_appointment(patient, language, doctor_index):
    if language in doctors and 0 <= doctor_index < len(doctors[language]):
        doctor_name = doctors[language][doctor_index]
        appointment = {'Patient': patient, 'Doctor': doctor_name, 'Time': datetime.datetime.now()}
        appointments.append(appointment)
        print(f"Appointment booked with {doctor_name} at {appointment['Time']}")
    else:
        print("Invalid doctor selection.")
def hospital_management():
    while True:
        print("\nHospital Management System")
        print("1. Sign Up")
        print("2. Login")
        print("3. Quit")

        choice = input("Enter your choice (1/2/3): ")

        if choice == '1':
            sign_up()
        elif choice == '2':
            if login():
                print("Login successful.")
                # Proceed with hospital management system
                while True:
                    print("\nHospital Management System")
                    print("1. Register Patient")
                    print("2. Choose the Location")
                    print("3. Select your problem")
                    print("4. Select Language and Doctor")
                    print("5. View Appointments")
                    print("6. Quit")

                    choice = input("Enter your choice (1/2/3/4/5/6): ")

                    if choice == '1':
                        register_patient()
                    elif choice == '2':
                        location()
                    elif choice == '3':
                        problem()
                    elif choice == '4':
                        language = input("Select Language (English/Hindi/Telugu/Kannada/Tamil): ").capitalize()
                        display_doctors(language)
                        doctor_index = int(input("Enter the number of the doctor you want to consult: ")) - 1
                        if 0 <= doctor_index < len(doctors[language]):
                            patient = patients[-1] if patients else None  # Get the latest registered patient
                            book_appointment(patient, language, doctor_index)
                        else:
                            print("Invalid doctor selection.")
                    elif choice == '5':
                        print("\nAppointments:")
                        for appointment in appointments:
                            print(f"Time: {appointment['Time']}, Patient: {appointment['Patient']}, Doctor: {appointment['Doctor']}")
                    elif choice == '6':
                        print("Thank you for using the Hospital Management System. Goodbye!")
                        break
                    else:
                        print("Invalid choice. Please enter a valid option.")
            else:
                print("Login failed.")
        elif choice == '3':
            print("Thank you for using the Hospital Management System. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter a valid option.")

hospital_management()

