# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Define valid usernames and passwords
valid_credentials = {'admin': 'admin123', 'user': 'password123'}

# Function for user login
def login():
    while True:
        username = input("Enter username: ")
        password = input("Enter password: ")

        # Check if username and password match
        if username in valid_credentials and valid_credentials[username] == password:
            print("Login successful!")
            return username
        else:
            print("Invalid username or password. Please try again.")

# Main function for the Hospital Management System
def hospital_management():
    # Perform login
    username = login()

    # Only proceed with the system if login is successful
    if username:
        while True:
            print("\nHospital Management System")
            print("1. Register Patient")
            print("2. Choose the Location")
            print("3. Select your problem")
            print("4. Select Language and Doctor")
            print("5. View Appointments")
            print("6. Logout")

            choice = input("Enter your choice (1/2/3/4/5): ")

            if choice == '1':
                register_patient()
            elif choice == '2':
                location()
            elif choice == '3':
                problem()
            elif choice == '4':
                language = input("Select Language (English/Hindi/Telugu/Kannada/Tamil): ").capitalize()
                display_doctors(language)
                doctor_index = int(input("Enter the number of the doctor you want to consult: ")) - 1
                if 0 <= doctor_index < len(doctors[language]):
                    patient = patients[-1] if patients else None  # Get the latest registered patient
                    book_appointment(patient, language, doctor_index)
                else:
                    print("Invalid doctor selection.")
            elif choice == '5':
                print("\nAppointments:")
                for appointment in appointments:
                    print(f"Time: {appointment['Time']}, Patient: {appointment['Patient']}, Doctor: {appointment['Doctor']}")
            elif choice == '6':
                print("Logout successful.")
                break
            else:
                print("Invalid choice. Please enter a valid option.")

# Entry point of the program
if __name__ == "__main__":
    hospital_management()

import getpass
import datetime

# Valid credentials dictionary
valid_credentials = {'admin': 'admin123', 'user': 'password123'}

# Function for user login
def login():
    while True:
        username = input("Enter username: ")
        password = getpass.getpass("Enter password: ")

        # Check if username and password match
        if username in valid_credentials and valid_credentials[username] == password:
            print("Login successful!")
            return username
        else:
            print("Invalid username or password. Please try again.")

# Data structures
patients = []
doctors = {
    'English': ["Dr.Sujith,contact NO:-885676545,Ratings:-(3/5)", "Dr.Raju,contact NO:-8653456987,Ratings:-(4/5)", "Dr.Raju,contact NO:-8653456987,Ratings:-(4/5)"],
    'Hindi': ["Dr.Kiran,contact NO:-213345678,Ratings:-(3.5/5)", "Dr.Naveen,contact NO:-754569878,Ratings:-(4.3/5)", "Dr.Jerina,contact NO:-63587458,Ratings:-(4.5/5)"],
    'Telugu':["Dr.Kajal,contact NO:-345678998,Ratings:-(4.5/5)","Dr.Nithish,contact NO:-754569878,Ratings:-(4.3/5)","Dr.Vaishnavi,contact NO:-63587458,Ratings:-(4.5/5)"],
    'Kannada':["Dr.Ramu,contact NO:-34567985,Ratings:-(3/5)","Dr.Varshini,contact NO:-345656987,Ratings:-(4/5)","Dr.Anuja,contact NO:-456780987,Ratings:-(3.5/5)"],
    'Tamil':["Dr.Manjunath,contact NO:-456780987,Ratings:-(4.3/5)","Dr.John,contact NO:--0987655689,Ratings:-(4.5/5)","Dr.John,contact NO:--0987655689,Ratings:-(4.5/5)"]
}
appointments = []

# Function to register a new patient
def register_patient():
    print("\nPatient Registration:")
    name = input("Enter Your Name: ")
    age = input("Enter Your Age: ")
    gender = input("Enter Your Gender: ")
    phone = input("Enter Your Phone Number: ")

    patient = {'Name': name, 'Age': age, 'Gender': gender, 'Phone': phone}
    patients.append(patient)
    print("Patient registered successfully!")

def location():
    while True:
        print("\nChoose Hospital location")
        print("1. HAL")
        print("2. MARATHAHALLI")
        print("3. KR PURA")

        choice = input("Enter your choice (1/2/3): ")

        if choice == '1':
            print("Your location is HAL")
            break
        elif choice == '2':
            print("Your location is MARATHAHALLI")
            break
        elif choice == '3':
            print("Your location is KR PURA")
            break
        else:
            print("Invalid choice. Please enter a valid option.")

def problem():
    while True:
        print("\nChoose your problem")
        print("1. Skin Diseases")
        print("2. Respiratory Issues")
        print("3. Heart Diseases")
        print("4. Thyroid Disorders")
        print("5. Diabetes")

        choice = input("Enter your choice (1/2/3/4/5): ")

        if choice == '1':
            print("I am Facing problem from Skin Diseases")
            break
        elif choice == '2':
            print("I am Facing problem Respiratory Issues")
            break
        elif choice == '3':
            print("I am Facing problem Heart Diseases")
            break
        elif choice == '4':
            print("I am Facing problem Thyroid Disorders")
            break
        elif choice == '5':
            print("I am Facing problem Diabetes")
            break
        else:
            print("Invalid choice. Please enter a valid option.")

# Function to display available doctors based on language
def display_doctors(language):
    if language in doctors:
        print(f"\nAvailable {language} Doctors:")
        for i, doctor in enumerate(doctors[language], start=1):
            print(f"{i}. {doctor}")
    else:
        print(f"No doctors available for {language}.")

# Function to book an appointment
def book_appointment(patient, language, doctor_index):
    if language in doctors and 0 <= doctor_index < len(doctors[language]):
        doctor_name = doctors[language][doctor_index]
        appointment = {'Patient': patient, 'Doctor': doctor_name, 'Time': datetime.datetime.now()}
        appointments.append(appointment)
        print(f"Appointment booked with {doctor_name} at {appointment['Time']}")
    else:
        print("Invalid doctor selection.")

# Main function for the Hospital Management System
def hospital_management():
    # Perform login
    username = login()

    # Only proceed with the system if login is successful
    if username:
        while True:
            print("\nHospital Management System")
            print("1. Register Patient")
            print("2. Choose the Location")
            print("3. Select your problem")
            print("4. Select Language and Doctor")
            print("5. View Appointments")
            print("6. Logout")

            choice = input("Enter your choice (1/2/3/4/5): ")

            if choice == '1':
                register_patient()
            elif choice == '2':
                location()
            elif choice == '3':
                problem()
            elif choice == '4':
                language = input("Select Language (English/Hindi/Telugu/Kannada/Tamil): ").capitalize()
                display_doctors(language)
                doctor_index = int(input("Enter the number of the doctor you want to consult: ")) - 1
                if 0 <= doctor_index < len(doctors[language]):
                    patient = patients[-1] if patients else None  # Get the latest registered patient
                    book_appointment(patient, language, doctor_index)
                else:
                    print("Invalid doctor selection.")
            elif choice == '5':
                print("\nAppointments:")
                for appointment in appointments:
                    print(f"Time: {appointment['Time']}, Patient: {appointment['Patient']}, Doctor: {appointment['Doctor']}")
            elif choice == '6':
                print("Logout successful.")
                break
            else:
                print("Invalid choice. Please enter a valid option.")

# Entry point of the program
if __name__ == "__main__":
    hospital_management()

